version: "3.9"

services:
  db_init:
    build: .
    volumes:
      - type: bind
        source: $ANNOTATOR_DB_FOLDER_PATH
        target: /app/db
    environment:
      - DB_PATH=/app/db/image_annotator.db
      - PHOTOS_DIR=/app/appss/static/images
    entrypoint: python appss/fllll.py create-database

  app:
    build: .
    depends_on:
      - db_init
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: $ANNOTATOR_DB_FOLDER_PATH
        target: /app/db
    entrypoint: gunicorn --chdir ./appss --bind 0.0.0.0:5000 wsgi:app
    environment:
      - DB_PATH=/app/db/image_annotator.db
      - PHOTOS_DIR=/app/appss/static/images
