version: "3.9"


services:
  db_init:
    build: .
    volumes:
      - type: bind
        source: $ANNOTATOR_DB_FOLDER_PATH
        target: /app/db
    entrypoint: python appss/fllll.py create-database

  app:
    build: .
    depends_on:
      - db_init
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: $ANNOTATOR_DB_FOLDER_PATH
        target: /app/db
    entrypoint: python appss/fllll.py start-app
